const actionTypes = {
    FETCH_PROFILE_DATA_FAILURE: 'FETCH_PROFILE_DATA_FAILURE',
    FETCH_PROFILE_DATA_SUCCESS: 'PROFILE_DATA_SUCCESS',
    FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
    TOGGLE_MODAL: 'TOGGLE MODAL',
    CHANGE_UPDATE_FIELD: 'CHANGE_UPDATE_FIELD',
};

export default actionTypes;
