const actionTypes = {
    FETCH_PROFILE_DATA: 'FETCH_PROFILE_DATA',
    FETCH_PROFILE_DATA_FAILURE: 'FETCH_PROFILE_DATA_FAILURE',
    PROFILE_DATA_SUCCESS: 'PROFILE_DATA_SUCCESS',
    TOGGLE_MODAL: 'TOGGLE MODAL',
};

export default actionTypes;
